2023-08-23 18:22:55,889:INFO-bot initialized from bot_init.py
2023-08-23 18:23:36,858:INFO-bot initialized from bot_init.py
2023-08-23 18:23:39,422:INFO-bot initialized from bot_init.py
2023-08-23 18:23:50,769:INFO-bot initialized from bot_init.py
2023-08-23 18:24:26,429:INFO-Retrieving info from the database from handle_inserted_image.py line 48
2023-08-23 18:24:26,443:ERROR-Exception occured in handle_inserted_image.py line 70
Traceback (most recent call last):
  File "d:\h_setup\fastapi-sqlalchemy-skeleton\tele_bot\missing_persons_functions\handle_inserted_image.py", line 58, in handle_inserted_image
    face_id=record[0]
TypeError: 'NoneType' object is not subscriptable
2023-08-23 18:25:19,719:INFO-Asking user for the person's name from handle_inserted_image.py line 40
2023-08-23 18:25:32,967:INFO-Asking for person's number from ask_phone.py
2023-08-23 18:25:43,312:INFO-Asking for person's age from ask_age.py line 17
2023-08-23 18:25:46,484:INFO-Asking user to enter person's address from ask_address.py line 16
2023-08-23 18:25:51,152:INFO-Validating the address from ask_identification.py line 16
2023-08-23 18:25:51,153:INFO-Asking user for the person's identification mark from ask_idetntification_mark.py line 19
2023-08-23 18:25:56,438:INFO-Inserting image into the database from enter_details.py line 25
2023-08-23 18:25:56,440:ERROR-Exception occured in enter_details.py line 43
Traceback (most recent call last):
  File "d:\h_setup\fastapi-sqlalchemy-skeleton\tele_bot\missing_persons_functions\details\enter_details.py", line 30, in enter_details
    CollectionId=dotenv_values('../.env')['CollectionId'],
KeyError: 'CollectionId'
2023-08-23 18:30:36,003:INFO-bot initialized from bot_init.py
2023-08-23 18:31:05,255:INFO-Asking user for the person's name from handle_inserted_image.py line 40
2023-08-23 18:31:10,072:INFO-Asking for person's number from ask_phone.py
2023-08-23 18:31:15,897:INFO-Asking for person's age from ask_age.py line 17
2023-08-23 18:31:19,795:INFO-Asking user to enter person's address from ask_address.py line 16
2023-08-23 18:31:27,077:INFO-Validating the address from ask_identification.py line 16
2023-08-23 18:31:27,082:INFO-Asking user for the person's identification mark from ask_idetntification_mark.py line 19
2023-08-23 18:31:31,158:INFO-Inserting image into the database from enter_details.py line 25
2023-08-23 18:31:31,158:ERROR-Exception occured in enter_details.py line 43
Traceback (most recent call last):
  File "d:\h_setup\fastapi-sqlalchemy-skeleton\tele_bot\missing_persons_functions\details\enter_details.py", line 30, in enter_details
    CollectionId=dotenv_values('../../.env')['CollectionId'],
KeyError: 'CollectionId'
2023-08-23 18:32:01,790:INFO-bot initialized from bot_init.py
2023-08-23 18:32:24,316:INFO-Asking user for the person's name from handle_inserted_image.py line 40
2023-08-23 18:32:28,509:INFO-Asking for person's number from ask_phone.py
2023-08-23 18:32:36,021:INFO-Asking for person's age from ask_age.py line 17
2023-08-23 18:32:39,359:INFO-Asking user to enter person's address from ask_address.py line 16
2023-08-23 18:32:43,906:INFO-Validating the address from ask_identification.py line 16
2023-08-23 18:32:43,907:INFO-Asking user for the person's identification mark from ask_idetntification_mark.py line 19
2023-08-23 18:32:49,819:INFO-Inserting image into the database from enter_details.py line 25
2023-08-23 18:32:49,819:ERROR-Exception occured in enter_details.py line 43
Traceback (most recent call last):
  File "d:\h_setup\fastapi-sqlalchemy-skeleton\tele_bot\missing_persons_functions\details\enter_details.py", line 30, in enter_details
    CollectionId=dotenv_values('.env')['CollectionId'],
KeyError: 'CollectionId'
2023-08-23 18:44:01,400:INFO-bot initialized from bot_init.py
2023-08-23 18:44:19,873:INFO-Asking user for the person's name from handle_inserted_image.py line 40
2023-08-23 18:44:25,498:INFO-Asking for person's number from ask_phone.py
2023-08-23 18:44:31,153:INFO-Asking for person's age from ask_age.py line 17
2023-08-23 18:44:34,018:INFO-Asking user to enter person's address from ask_address.py line 16
2023-08-23 18:44:38,312:INFO-Validating the address from ask_identification.py line 16
2023-08-23 18:44:38,313:INFO-Asking user for the person's identification mark from ask_idetntification_mark.py line 19
2023-08-23 18:44:43,154:INFO-Inserting image into the database from enter_details.py line 25
2023-08-23 18:45:04,690:INFO-Retrieving info from the database from handle_inserted_image.py line 48
2023-08-23 18:45:11,659:INFO-Asking for the reciever's name from handle_inserted_image.py line 89
2023-08-23 18:45:17,023:INFO-Asking for user phone number from ask_reciver_name.py
2023-08-23 18:45:23,007:INFO-Sending a greet message from ask_reciever_phone.py
2023-08-23 18:45:23,511:INFO-Inserting reciever's details from ask_reciever_phone.py
